### ISSUE TITLE
toggle per-app interception mode on main app list

### ISSUE THREAD

**Issue by mnjm97** [CollegeDev/DonkeyGuard#20]
possibly move enabling logs to the settings and use the toggle button for enabling interception...

**Comment by CollegeDev** [comment]
So the intention of this is to have a "batch-switch" which enables the interception mode (on demand dialog) for all permissions of the application? Did I get it?

**Comment by mnjm97** [comment]
thats what i was thinking...

**Comment by xdxita** [comment]
If accepted, add an option to enable by default for new installed apps.

**Comment by CollegeDev** [comment]
Both accepted. It can take a while, because I'm currently working on the logging feature, which is quite a lot of work. Please take that in mind while waiting.

**Comment by CollegeDev** [comment]
@xdxita implemented in v0.5.51
@mnjm97 your request will come within the next release.
//edit implemented in v0.5.52 -> if something is missing, please open a new issue.
