### ISSUE TITLE
Comparison with Xprivacy

### ISSUE THREAD

**Issue by dandv** [CollegeDev/DonkeyGuard#23]
How does this module compare with Xprivacy?

**Comment by CollegeDev** [comment]
Well, this should not be discussed in an issue!
Please take a look [here](http://forum.xda-developers.com/showpost.php?p=55000518&postcount=93) and [here](http://forum.xda-developers.com/showpost.php?p=54893140&postcount=69).
If you want to know more about this, please simply ask on my XDA-Thread.

**Comment by dandv** [comment]
Agree, this should not be discussed in an issue. It should be mentioned in the README.
