### ISSUE TITLE
App is crashing - LG G3 D855

### ISSUE THREAD

**Issue by geroxx** [CollegeDev/DonkeyGuard#28]
The app is crashing after the message "Check it out" appeared.
The logs in Xposed were empty.

Logcat: http://pastebin.com/sP3BKj5i

**Comment by CollegeDev** [comment]
Looks like an error inside one of the used libraries (maybe a compiling issue). Which version do you use? Please simply deinstall DonkeyGuard, download the newest version (v0.5.52 via xposed repo) and try again.

**Comment by geroxx** [comment]
i already had installed the newest version (v0.5.52). I re-installed DonkeyGuard but the problem still exist. But the problem already exists in the first version i used (v0.5.50)
Maybe an app interfere with DonkeyGuard? In the next days i will reinstall android so i can make sure if an app interfere with DonkeyGuard.

**Comment by CollegeDev** [comment]
It is a known error from a library I'm using. I will looking forward to fix that problem. It is only at the last step where it happens, right?

**Comment by geroxx** [comment]
When i click the "Next"-button fast enough it seems i can skip the "Check it out" message.
Then when i go into "Settings" from an app inside DonkeyGuard i can go next until the "Permissions" message. Here it crashs again.
![screenshot_2014-09-12-13-03-20](https://cloud.githubusercontent.com/assets/3219220/4248843/946ab21c-3a6c-11e4-81d1-b808d71b3b68.png)

**Comment by CollegeDev** [comment]
Please try v0.5.53 and report if it works for your.

**Comment by geroxx** [comment]
The latest version fixed the problem. Thank you very much for your effort!
