### ISSUE TITLE
Drawing power menu over permission prompt 

### ISSUE THREAD

**Issue by ghost** [CollegeDev/DonkeyGuard#43]
Could this be done? I take screenshots via the power menu, but DG draws on top of anything? Preferably implemented via an option for the application. 

Kind Regards 
TwinAdk

**Comment by ghost** [comment]
Just noticed the other day that DG draws on top of the locksceeen.. I'm like wow, doesn't that require permissions or is that part of the 'draw above EVERYTHING policy'? :-)

Just curious.. 

Twin

**Comment by CollegeDev** [comment]
You already mentioned it. It is just a part of the "draw above EVERYTHING policy".
I need to take a look at the android framework to find out if your request is technically feasible. 

But please note: Drawing the dialog at a lower level of the view hierarchy may causes that malicious applications can simply draw their dialogs above the prompt dialog of DG.

**Comment by ghost** [comment]
Very well, i can accept a solution that is to map a hardware button to screenshots, should i need to screenshot DG. I do not wish to lower the functionality of DG.
