### ISSUE TITLE
Feature request: Network access control

### ISSUE THREAD

**Issue by schertling** [CollegeDev/DonkeyGuard#6]
General (undistinctive) network access permission handling would be great to avoid using additional firewall apps.

**Comment by CollegeDev** [comment]
Should be possible. But: no fine-tuning. Just as simple as a switch: Can access internet or not.
Furthermore it will take some time.

**Comment by schertling** [comment]
Bestens

**Comment by CollegeDev** [comment]
Well, I've made some "testings" until now. The current state:
Internet-restriction is possible and works so far (not activated in DG until now), but with a little exception. If the application is using  a connection-based protocol to connect e.g. to a server, you can't restrict it directly. That means: If the application is currently connected to a server and you restrict internet access, the rule will be applied after the restart of the application. I think this shouldn't happen. I will looking forward to develop a solution for this behavior.

**Comment by schertling** [comment]
You mean that an existing connection won't be disconnected by the rule, just reestablishing will be blocked ever after? I think that's a reasonable restriction for the beginning and still far better than using an extra app.

**Comment by CollegeDev** [comment]
> You mean that an existing connection won't be disconnected by the rule, just reestablishing will be blocked ever after?

Exactly.

> I think that's a reasonable restriction for the beginning and still far better than using an extra app.

Okay, I will release it asap.

**Comment by CollegeDev** [comment]
Implemented in (v0.5.49, please take a look at the changelog for further information). If something is missing or not working, please open a new issue.
