### ISSUE TITLE
Feature request: Initial permissions setting on app demand by popup

### ISSUE THREAD

**Issue by schertling** [CollegeDev/DonkeyGuard#7]
After adding an app to DonkeyGuard surveillance:
Each initial access request of the app to any single permission which has not yet been indexed in the database provides a popup offering the possible options for permanent use. This is a one time action per permission per app. In this way the permission database grows according to actual usage.
Subsequent modifications are managed by the standard settings dialog showing the current settings.

Idea initially introduced by mnjm9b on xda-developers forum.

Add on:
The popup dialog offers explanation and hints for the issue concerned.

**Comment by CollegeDev** [comment]
Sounds good. I have to check if it is possible with the current architecture.

**Comment by CollegeDev** [comment]
Should be implemented in v0.5.49. If something is missing, please open a new feature request. Thanks.
