### ISSUE TITLE
GPS failure

### ISSUE THREAD

**Issue by schertling** [CollegeDev/DonkeyGuard#9]
Simply installing and activating DG lets GPS fail although satellites get fix. Deactivating DG restores function.
i9300 rooted stock 4.3 and others

**Comment by Confectrician** [comment]
Can't confirm this in Xperia Z (C6603).
GPS works fine here wird activated DG. 

I am running the eXistenZ custom ROM (4.4.2)

**Comment by CollegeDev** [comment]
Okay, that sounds curious. To track this down I need the full log of the XposedFramework and Catlog while the GPS doesn't work. If some of you won't post the log in public, just send it to me via PM on XDA.

**Comment by Confectrician** [comment]
I have to cancel my Post from above.
Had to chance to test this in detail again.

It seems that it worked this morning because the position could be searched with wlan.
I recorded a log and will send it to you later.

**Comment by schertling** [comment]
Makes no difference with me, I have 14 fixes and wlan but no position.
Sent logs via PN.

**Comment by CollegeDev** [comment]
Should be fixed. Please download the App from http://forum.xda-developers.com/showpost.php?p=54925314&postcount=76 and confirm if it works for you.

**Comment by schertling** [comment]
It's working now as far as  I've tested it.

**Comment by CollegeDev** [comment]
Good!
